services:

  readsb:
    container_name: readsb
    image: ghcr.io/tyz/readsb:latest
    restart: unless-stopped
    volumes:
      - /dev/bus/usb:/dev/bus/usb:ro
      - ./data:/data:rw
    environment:
      CLI_ARGS: >
       --device-type rtlsdr
       --gain 25
       --lat 51.889997,
       --lon 1.476164,
       --write-json /data
       --write-json-every 1
       --net
       --bus-multiplier 1.0
       --json-location-accuracy 2

  tar1090:
    container_name: tar1090
    image: ghcr.io/tyz/tar1090:latest
    restart: unless-stopped
    volumes:
      - ./data:/usr/share/nginx/html/data:rw
