name: Build Docker image (ARM64)

on:
  push:
    branches: [master]
    paths:
      - 'Dockerfile'
      - 'Dockerfile.tar1090'
      - 'docker/**'
      - '.github/workflows/build-arm64.yaml'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  READSB_IMAGE_NAME: ${{ github.repository_owner }}/readsb
  TAR1090_IMAGE_NAME: ${{ github.repository_owner }}/tar1090

jobs:
  docker-build:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: readsb
            file: Dockerfile
            repo_url: https://raw.githubusercontent.com/wiedehopf/readsb/master/version
          - name: tar1090
            file: Dockerfile.tar1090
            repo_url: https://raw.githubusercontent.com/wiedehopf/tar1090/master/version

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Extract the version
        id: version
        run: |
          VERSION=$(curl -s ${{ matrix.repo_url }})
          echo "app_version=${VERSION}" | tee -a $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Login to the Container registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ matrix.name }}
          tags: |
            type=raw,value=latest
            type=sha,prefix=sha-
            type=raw,value=${{ steps.version.outputs.app_version }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.file }}
          push: ${{ github.event_name != 'pull_request' }}
          provenance: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=docker-${{ matrix.name }}
          cache-to: type=gha,mode=max,scope=docker-${{ matrix.name }}
